[package]
name = "io"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.21"
actix-cors = "0.6.0-beta.8"
actix-http = "3.0.0-beta.19"
actix-service = "2.0"
actix-web-httpauth = "0.6.0-beta.7"

reqwest = { version = "0.11", features = ["json", "stream"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

pretty_env_logger = "0.4.0"

jsonwebtoken = "7"

chrono = "0.4" 