[package]
name = "io"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.3"
actix-cors = "0.6.0-beta.9"
actix-http = "3.0.0-rc.4"
actix-service = "2.0"
actix-web-httpauth = "0.6.0-beta.8"
tokio = { version = "1.13.1", features = ["rt-multi-thread", "macros"] }

reqwest = { version = "0.11", features = ["json", "stream"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

pretty_env_logger = "0.4.0"
log = "0.4"

jsonwebtoken = "7"

chrono = "0.4" 

diesel = { version = "1.4", features = ["postgres", "r2d2"] }

rust-argon2 = "1.0"

uuid = { version = "0.8", features = ["v4"] }

sysinfo = "0.23"

futures = "0.3"

thiserror = "1.0"

async-trait = "0.1.52"

anitomy = "0.1"